In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn

In [2]:
temp = torch.FloatTensor([2])
temp.ndim

1

### Vector

In [3]:
temp = torch.FloatTensor([23,24,24.5,26,27.2,23.0])
temp.size()

torch.Size([6])

In [4]:
temp

tensor([23.0000, 24.0000, 24.5000, 26.0000, 27.2000, 23.0000])

In [5]:
temp = torch.IntTensor([23,24,24.5,26,27.2,23.0])
temp.size()

torch.Size([6])

In [6]:
temp

tensor([23, 24, 24, 26, 27, 23], dtype=torch.int32)

### Scalar

In [7]:
x = torch.rand(10)
x.size()

torch.Size([10])

In [8]:
x

tensor([0.3143, 0.0458, 0.9253, 0.3708, 0.5707, 0.4433, 0.0075, 0.4942, 0.7528,
        0.6807])

### Matrix

In [9]:
df = pd.read_csv("C:/Training/Academy/Statistics (Python)/Cases/Concrete Strength/Concrete_Data.csv")
df.head()

Cement  Blast  Fly  Water  Superplasticizer  Coarse   Fine  Age  Strength
0   540.0    0.0  0.0  162.0               2.5  1040.0  676.0   28     79.99
1   540.0    0.0  0.0  162.0               2.5  1055.0  676.0   28     61.89
2   332.5  142.5  0.0  228.0               0.0   932.0  594.0  270     40.27
3   332.5  142.5  0.0  228.0               0.0   932.0  594.0  365     41.05
4   198.6  132.4  0.0  192.0               0.0   978.4  825.5  360     44.30

In [10]:
df.values

array([[540.  ,   0.  ,   0.  , ..., 676.  ,  28.  ,  79.99],
       [540.  ,   0.  ,   0.  , ..., 676.  ,  28.  ,  61.89],
       [332.5 , 142.5 ,   0.  , ..., 594.  , 270.  ,  40.27],
       ...,
       [148.5 , 139.4 , 108.6 , ..., 780.  ,  28.  ,  23.7 ],
       [159.1 , 186.7 ,   0.  , ..., 788.9 ,  28.  ,  32.77],
       [260.9 , 100.5 ,  78.3 , ..., 761.5 ,  28.  ,  32.4 ]])

In [11]:
df_tensor = torch.from_numpy(df.values)
df_tensor.size()

torch.Size([1030, 9])

In [12]:
df_tensor[:2]

tensor([[ 540.0000,    0.0000,    0.0000,  162.0000,    2.5000, 1040.0000,
          676.0000,   28.0000,   79.9900],
        [ 540.0000,    0.0000,    0.0000,  162.0000,    2.5000, 1055.0000,
          676.0000,   28.0000,   61.8900]], dtype=torch.float64)

In [13]:
a = np.array([4,6,7])
b = np.array([5,8,1])
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [14]:
ta = torch.from_numpy(a)
ta

tensor([4, 6, 7], dtype=torch.int32)

In [15]:
tb = torch.from_numpy(b)
tb

tensor([5, 8, 1], dtype=torch.int32)

In [16]:
ta+tb

tensor([ 9, 14,  8], dtype=torch.int32)

In [17]:
torch.sum(ta)

tensor(17)

In [18]:
ta = ta.to(torch.float32)
print(ta.dtype)

torch.float32


In [19]:
ta.device

device(type='cpu')

### Reshaping

In [20]:
a = np.array([[4,6,7],
            [6,8,9]])
a.shape

(2, 3)

In [21]:
a.reshape(3,2)

array([[4, 6],
       [7, 6],
       [8, 9]])

In [22]:
ta = torch.from_numpy(a)
ta.view(3,2)

tensor([[4, 6],
        [7, 6],
        [8, 9]], dtype=torch.int32)

### Transpose

In [23]:
a.T

array([[4, 6],
       [6, 8],
       [7, 9]])

In [24]:
ta.T

tensor([[4, 6],
        [6, 8],
        [7, 9]], dtype=torch.int32)